apiVersion: v1        # kubectl API version
kind: Service             # Type of kubernetes resource
metadata :            # Metadata about the service
  name: ngnix-clusterip
spec:
    type: clusterIP
    selector:
        app: my-nginx
    ports:
        - port: 8080
          targetPort: 80




## kubectl get services
## kubectl get services