apiVersion: v1        # kubectl API version
kind: Service             # Type of kubernetes resource
metadata :            # Metadata about the service
  name: my-service
  labels:
    app: my-service
spec:
    selector:   # Service will apply to resources with a label of app: my-service
      app: my-service
    ports:   # Define container target port(s) and the ports for Service
      - name: http
        port: 80
        targetPort: 8080
        protocol: TCP

##