#DOCKERFILE  - bluepring for building images
FROM  alpine:3.6

RUN   mkdir -p /home/app # Directory is created INSIDE the container NOT on laptop(host)
COPY .home/app   # Execute on the HOST machine
CMD ["node","server.js"] # Execute on the container


#bluepring for building images
#docker build -t my-app:1.0
#docker build -t my-app:1.0
#docker images
#docker ps -a | grep my-app
#docker rm <container_id>
#docker rmi <container_id>
#docker exec -it <container_id> /bin/sh
    # ls
    # env
    # ls /home/app/
