apiVersion: v1        # kubectl API version
kind: Service             # Type of kubernetes resource
metadata :            # Metadata about the service
  name: ngnix-loadbalancer # Name of the service
spec:
    type: LoadBalancer
    selector:
        app: my-nginx
    ports:
        - name: 80
          Port: 80 # external port
          targetPort: 80




## kubectl get services
## kubectl apply -f loadbalancer.service.yml
## kubectl get services