apiVersion: v1        # kubectl API version
kind: Pod             # Type of kubernetes resource
metadata :            # Metadata about the Pos
  name: my-nginx
spec:                 # The spec / blueprint of the Pod
  containers:         # Information about the containers that will run in the Pod
    - name: my-nginx
      image: nginx:alpine

##