apiVersion: v1        # kubectl API version
kind: Service             # Type of kubernetes resource
metadata :            # Metadata about the service
  name: ngnix-nodeport
spec:
    type: NodePort
    selector:
        app: my-nginx
    ports:
        - port: 80
          targetPort: 80
          nodePort: 31000




## kubectl get services
## kubectl apply -f nodeport.service.yml
## kubectl get services