#define a persistentVolumeClaim.yaml file
kind: PersistentVolumeClaim    # define a PVC
apiVersion: v1
metadata:
  name:pv-dd-account-hdd-5g
  annotations:
    volume.beta.kubernetes.io/storage-class: accounthdd
spec:
  accessModes:  # Define access Mode
    - ReadWriteOnce     # one client can mount for read/writ
  resources:
    requests:   # Requested storage amount
      storage: 5Gi



#https://github.com/kubernetes/examples:









# kubectl apply -f nginx-alpine-emptyDirpod.yaml
# kubectl port-forward nginx-alpine-volume 8080:80