apiVersion: v1        # kubectl API version
kind: Service             # Type of kubernetes resource
metadata :            # Metadata about the service
spec:
    type:       ## Type of service (clusterIP, Nodeport, LoadBalancer, ...) default: ClusterIP

    selector:  ## Select Pod template labels that service will apply to

    ports:    # Define container target port and the port for the service

##