version:3
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mango-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    volumes:
      - mango-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

# List all the volumes you are using in any of your containers
volumes:
  mango-data:
    driver: local

## docker-compose -f mongo.yaaml up
## docker-compose -f mongo.yaaml down
## docker-compose ps
## docker network ls
