version:3
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mango-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    volumes:
      - mango-data:/data/db
    environment:
      - ME_CONFIG_MONGODB_INITDB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

# List all the volumes you are using in any of your containers
volumes:
  mango-data:
    driver: local

## docker-compose -f mongo.yaml up
## docker-compose -f mongo.yaml down
## docker-compose ps
## docker-compose  exec -it 44c8a3e902ca sh
## ls /data/db
## docker network ls

# 1 host-volume-name
# 2 path-inside-of-the-container
## mysql : var/lib/mysql
## postgresss : /data/db
## mongo : var/lib/postgress/data
## This path differs for each database
## docker-compose -f docker-compose.yaml down
## docker-compose -f docker-compose.yaml  up